import type {
  BacktestMetric,
  CountryIndexEntry,
  CountryOverview,
  CountryTimeseries,
  EnergyIndicator,
  RegimeDiagnostic,
  RiskComponent,
  RunMetadata,
  ScenarioQuantile,
  WebManifest,
} from '../lib/schemas'

export const fixtureCountries: CountryIndexEntry[] = [
  { country_iso3: 'AAA', country_name: 'Alphaland', region: 'Test Region', income_group: 'High income' },
  { country_iso3: 'BBB', country_name: 'Betaland', region: 'Test Region', income_group: 'Upper middle income' },
]

export const fixtureCountryOverview: CountryOverview[] = [
  {
    country_iso3: 'AAA',
    country_name: 'Alphaland',
    g20_flag: true,
    region: 'Test Region',
    income_group: 'High income',
    valid_from: '2000-01-01',
    valid_to: null,
    score_version: 'v2_energy',
    component_version: 'energy_component_v2.1',
    weights_version: 'v2_weights_v1',
    score_total: 35.0,
    score_pace: 30.0,
    score_coupling: 40.0,
    score_volatility: 50.0,
    score_forward_downside: 35.0,
    score_energy: 20.0,
    energy_confidence: 100.0,
    data_confidence_score: 90.0,
    weight_coverage: 1.0,
    rank: 2,
    rank_band: 'moderate',
    score_total_v1: 40.0,
    rank_v1: 2,
    latest_transition_year: 2024,
    carbon_intensity_gdp: 0.9,
    co2_per_capita: 5.0,
    energy_intensity_gdp: 2.0,
    is_core_complete: true,
    missing_feature_count: 0,
    transition_snapshot_id: 'snap-a',
    latest_energy_year: 2024,
    coal_share_elec: 20.0,
    fossil_share_elec: 50.0,
    low_carbon_share_elec: 50.0,
    renewables_share_elec: 30.0,
    transition_velocity: 1.2,
    stalled_transition_residual_pp: 0.0,
    active_score_version: 'v2_energy',
    is_active_score: true,
    score_delta_v2_minus_v1: -5.0,
    rank_delta_v2_minus_v1: 0,
    risk_segment: 'Medium transition risk',
    latest_successful_run_id: 'run-1',
    latest_successful_run_completed_at: '2026-01-01T00:05:00Z',
    publish_status: 'PUBLISHED',
    bi_version: 'bi_semantic_v1',
  },
  {
    country_iso3: 'BBB',
    country_name: 'Betaland',
    g20_flag: true,
    region: 'Test Region',
    income_group: 'Upper middle income',
    valid_from: '2000-01-01',
    valid_to: null,
    score_version: 'v2_energy',
    component_version: 'energy_component_v2.1',
    weights_version: 'v2_weights_v1',
    score_total: 75.0,
    score_pace: 80.0,
    score_coupling: 75.0,
    score_volatility: 60.0,
    score_forward_downside: 85.0,
    score_energy: 90.0,
    energy_confidence: 95.0,
    data_confidence_score: 40.0,
    weight_coverage: 0.9,
    rank: 1,
    rank_band: 'high',
    score_total_v1: 70.0,
    rank_v1: 1,
    latest_transition_year: 2024,
    carbon_intensity_gdp: 1.5,
    co2_per_capita: 8.0,
    energy_intensity_gdp: 3.0,
    is_core_complete: true,
    missing_feature_count: 1,
    transition_snapshot_id: 'snap-a',
    latest_energy_year: 2024,
    coal_share_elec: 60.0,
    fossil_share_elec: 85.0,
    low_carbon_share_elec: 15.0,
    renewables_share_elec: 5.0,
    transition_velocity: -0.5,
    stalled_transition_residual_pp: 2.0,
    active_score_version: 'v2_energy',
    is_active_score: true,
    score_delta_v2_minus_v1: 5.0,
    rank_delta_v2_minus_v1: 0,
    risk_segment: 'High transition risk',
    latest_successful_run_id: 'run-1',
    latest_successful_run_completed_at: '2026-01-01T00:05:00Z',
    publish_status: 'PUBLISHED',
    bi_version: 'bi_semantic_v1',
  },
]

export const fixtureCountryTimeseries: CountryTimeseries[] = [
  {
    country_iso3: 'AAA',
    year: 2023,
    co2_mt: 100,
    real_gdp: 1000,
    secondary_gdp_owid: 900,
    population: 10,
    carbon_intensity_gdp: 1.0,
    co2_per_capita: 5,
    energy_intensity_gdp: 2,
    primary_energy_twh: 30,
    is_core_complete: true,
    missing_feature_count: 0,
    imputation_mask: '',
    snapshot_set_id: 'snap-a',
    coal_share_elec: 20,
    gas_share_elec: 30,
    oil_share_elec: 5,
    fossil_share_elec: 55,
    renewables_share_elec: 30,
    low_carbon_share_elec: 45,
    nuclear_share_elec: 15,
    solar_share_elec: 7,
    wind_share_elec: 8,
    hydro_share_elec: 10,
    biofuel_share_elec: 5,
    snapshot_set_id_energy: 'snap-a-energy',
    country_name: 'Alphaland',
    region: 'Test Region',
    income_group: 'High income',
    bi_version: 'bi_semantic_v1',
  },
]

export const fixtureRiskComponents: RiskComponent[] = [
  {
    country_iso3: 'AAA',
    score_version: 'v2_energy',
    component_name: 'pace',
    component_score: 30.0,
    nominal_weight: 0.2,
    effective_weight: 0.2,
    is_active_score: true,
    component_version: 'energy_component_v2.1',
    weights_version: 'v2_weights_v1',
    bi_version: 'bi_semantic_v1',
  },
]

export const fixtureScenarioQuantiles: ScenarioQuantile[] = [
  {
    country_iso3: 'AAA',
    origin_year: 2024,
    target_year: 2030,
    scenario_horizon_years: 6,
    scenario_method: 'empirical_bootstrap_v1',
    scenario_status: 'production',
    forecast_p05: 0.5,
    forecast_p50: 0.8,
    forecast_p95: 1.2,
    deterministic_baseline: 0.85,
    prob_below_origin_value: 0.6,
    simulation_count: 10000,
    random_seed: 42,
    experimental_variant: false,
    bi_version: 'bi_semantic_v1',
    country_name: 'Alphaland',
    region: 'Test Region',
    income_group: 'High income',
  },
]

export const fixtureBacktestMetrics: BacktestMetric[] = [
  {
    model_variant: 'empirical_bootstrap',
    n_splits: 6,
    mae: 0.05,
    rmse: 0.06,
    median_ae: 0.04,
    coverage_90: 0.76,
    mean_interval_width_90: 0.2,
    metric_grain: 'summary',
    nominal_coverage_90: 0.9,
    calibration_gap_90: 0.14,
    absolute_error: null,
    actual: null,
    country_iso3: null,
    covered_90: null,
    forecast_p05: null,
    forecast_p50: null,
    forecast_p95: null,
    horizon_years: null,
    interval_width_90: null,
    origin_year: null,
    target_year: null,
    production_model_variant: 'empirical_bootstrap',
    bi_version: 'bi_semantic_v1',
  },
]

export const fixtureEnergyIndicators: EnergyIndicator[] = [
  {
    country_iso3: 'AAA',
    year: 2024,
    coal_share_elec: 20,
    gas_share_elec: 30,
    oil_share_elec: 5,
    fossil_share_elec: 55,
    renewables_share_elec: 30,
    low_carbon_share_elec: 45,
    nuclear_share_elec: 15,
    solar_share_elec: 7,
    wind_share_elec: 8,
    hydro_share_elec: 10,
    biofuel_share_elec: 5,
    snapshot_set_id: 'snap-a-energy',
    country_name: 'Alphaland',
    region: 'Test Region',
    income_group: 'High income',
    latest_feature_latest_year: 2024,
    latest_feature_trailing_window_years: 5,
    latest_feature_sample_size: 5,
    latest_feature_coal_share_elec: 20,
    latest_feature_fossil_share_elec: 55,
    latest_feature_renewables_share_elec: 30,
    latest_feature_low_carbon_share_elec: 45,
    latest_feature_coal_trend_pp_per_year: -0.5,
    latest_feature_clean_power_momentum_pp_per_year: 1.0,
    latest_feature_renewable_buildout_rate_pp_per_year: 0.8,
    latest_feature_fossil_persistence_mean_pct: 55,
    latest_feature_transition_velocity: 1.2,
    latest_feature_stalled_transition_residual_pp: 0.0,
    latest_feature_coal_share_elec_percentile: 50,
    latest_feature_low_carbon_share_elec_percentile: 50,
    bi_version: 'bi_semantic_v1',
  },
]

export const fixtureRegimeDiagnostics: RegimeDiagnostic[] = [
  {
    country_iso3: 'AAA',
    series_name: 'carbon_intensity_gdp',
    as_of_year: 2024,
    latest_regime_start_year: 2018,
    years_in_current_regime: 6,
    break_count: 1,
    strongest_break_year: 2018,
    strongest_break_strength: 2.0,
    pre_break_slope: -0.01,
    post_break_slope: -0.03,
    slope_delta: -0.02,
    regime_direction: 'IMPROVING',
    regime_confidence: 0.8,
    current_regime_label: 'ACCELERATING_TRANSITION',
    break_method: 'segmented_regression',
    break_version: 'm7_regime_break_v0.1',
    country_name: 'Alphaland',
    region: 'Test Region',
    income_group: 'High income',
    diagnostic_status: 'diagnostic_only_not_production_forecast_selector',
    used_in_production_score: false,
    used_in_production_scenario: false,
    bi_version: 'bi_semantic_v1',
  },
]

export const fixtureRunMetadata: RunMetadata = {
  run_id: 'run-1',
  started_at: '2026-01-01T00:00:00Z',
  completed_at: '2026-01-01T00:05:00Z',
  generated_at: '2026-01-01T00:05:00Z',
  publish_status: 'PUBLISHED',
  active_score_version: 'v2_energy',
  component_version: 'energy_component_v2.1',
  weights_version: 'v2_weights_v1',
  production_scenario_method: 'empirical_bootstrap_v1',
  git_sha: 'abc123def456',
  image_ref: 'ghcr.io/example/climate-risk:abc123',
  image_digest: 'sha256:deadbeef',
  config_hash: 'cfg-hash',
  transition_snapshot_id: 'snap-a',
  owid_co2_snapshot_id: 'co2-snap',
  world_bank_wdi_snapshot_id: 'wdi-snap',
  owid_energy_snapshot_id: 'energy-snap',
  latest_model_eligible_year: 2024,
  latest_model_eligible_year_completeness: 1.0,
  bi_version: 'bi_semantic_v1',
}

export const fixtureManifest: WebManifest = {
  schema_version: '1.0.0',
  generated_at: '2026-01-02T00:00:00Z',
  source_run_id: 'run-1',
  source_git_sha: 'abc123def456',
  active_score_version: 'v2_energy',
  active_component_version: 'energy_component_v2.1',
  active_scenario_method: 'empirical_bootstrap_v1',
  model_eligible_year: 2024,
  country_count: 2,
  source_snapshot_ids: { owid_co2: 'co2-snap', world_bank_wdi: 'wdi-snap', owid_energy: 'energy-snap' },
  config_hash: 'cfg-hash',
  web_bundle_hash: 'deadbeef'.repeat(8),
  files: [{ name: 'country-overview.json', row_count: 2, sha256: 'a'.repeat(64), schema_version: '1.0.0' }],
}

export const fixtureBundle: Record<string, unknown> = {
  'manifest.json': fixtureManifest,
  'countries.json': fixtureCountries,
  'country-overview.json': fixtureCountryOverview,
  'country-timeseries.json': fixtureCountryTimeseries,
  'risk-components.json': fixtureRiskComponents,
  'scenario-quantiles.json': fixtureScenarioQuantiles,
  'backtest-metrics.json': fixtureBacktestMetrics,
  'energy-indicators.json': fixtureEnergyIndicators,
  'regime-diagnostics.json': fixtureRegimeDiagnostics,
  'run-metadata.json': [fixtureRunMetadata],
}

export function installFetchMock(overrides: Record<string, unknown> = {}) {
  const bundle = { ...fixtureBundle, ...overrides }
  vi.stubGlobal(
    'fetch',
    vi.fn(async (input: string | URL) => {
      const url = typeof input === 'string' ? input : input.toString()
      const fileName = Object.keys(bundle).find((name) => url.endsWith(name))
      if (!fileName) {
        return new Response('not found', { status: 404 })
      }
      return new Response(JSON.stringify(bundle[fileName]), {
        status: 200,
        headers: { 'Content-Type': 'application/json' },
      })
    }),
  )
}
